### ISSUE TITLE
Display related knowledgebase (post or custom post type) entries before submit

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#100]
I have a feature request:
When user enters the title, the system should automatically (ajax) search for equal/related and  show  the best 5 of them (if 5 are available).

e.g.

User types "How can I setup the system?"
The system should now display entries like:
- How to setup the system?
- Issue on setting up the system
...

Thank you :)

**Comment by julien731** [comment]
This will be coming in the FAQ add-on: https://trello.com/c/eY81zQsY
