### ISSUE TITLE
stakeholder bug

### ISSUE THREAD

**Issue by rudashi** [ThemeAvenue/Awesome-Support#112]
Hello,

If you delete an user account, editing ticket give an error with file stakeholders.php.
Lines that cause an error:
`$issuer_id = $issuer->data->ID;`
`$issuer_name = $issuer->data->display_name;`

I created temporary solution, but you need to check this out:

```
if ($issuer !== false) {
	$issuer_id = $issuer->data->ID;
	$issuer_name = $issuer->data->display_name;
} else {
	$issuer_id = 0;
	$issuer_name = 'deleted user';
}
```

**Comment by SiamKreative** [comment]
Thanks for contributing @rudashi

Feel free to fork our plugin for bug fixes or improvements. You'll appear on the [team page](http://getawesomesupport.com/team/) if your fork gets merged :)

**Comment by rudashi** [comment]
@SiamKreative please check:
commit: eeb56c65faabe248b7dcac2d1c24847b675d5062
