### ISSUE TITLE
Changed main page to subpage causing wrong links and 404

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#114]
At installation I used this page for all tickets page (containing `[tickets]`):
`site.com/tickets` and `site.com/ticket/%ticket-name%` was the url for single tickets.

Now I changed the page to be a child page of `support` so the new url should be `site.com/support/tickets` and `site.com/support/ticket/%ticket-name`

But all links in admin panel and email are still linking to `site.com/ticket/%ticket-name%` and lead to a 404 error....

How can I fix this?

I already saved the options in backend and also saved the permalink settings...

**Comment by julien731** [comment]
The `site.com/ticket/%ticket-name%` is how WordPress handles custom post types. If you want to use a custom prefix you might have to add a new rewrite rule. You should Google it around.

Regarding the 404 page, did you try to refresh the permalinks?

**Comment by TheZoker** [comment]
> Regarding the 404 page, did you try to refresh the permalinks?

> I already saved the options in backend and also **saved the permalink settings**...

**Comment by julien731** [comment]
My bad I missed that. Do you only have the 404 with the URL structure you're trying to use or with every URL structure?

**Comment by TheZoker** [comment]
Problem solved (dont know why :P)
