### ISSUE TITLE
Adding another email API - Mandrill

### ISSUE THREAD

**Issue by calvintam236** [ThemeAvenue/Awesome-Support#116]
Please add support for this service: https://mandrill.com

**Comment by SiamKreative** [comment]
What's the point of integrating with Mandrill while there's a [great plugin](https://wordpress.org/plugins/wpmandrill/) for this? What's your idea for the integration?

This is actually what we use internally.

**Comment by calvintam236** [comment]
In the plugin it said, "You can enable e-mail checking on the registration page. When enabled, the plugin will make sure the e-mail address used is valid and can receive e-mails. The verification is done using Email validation API and requires a (free) MailGun account. This helps reducing typos in email addresses during sign ups."
Since Mandrill is more popular in my country (United States) and it is better than MailGun, why don't support both? (We love MailChimp's service so many companies prefer it and Mandrill here.)

Ref.: https://www.ventureharbour.com/transactional-email-service-best-mandrill-vs-sendgrid-vs-mailjet/

**Comment by julien731** [comment]
Oh I see. There is actually no MailGun integration in the plugin, we just use their e-mail verification tool that's all. We do not plan to add e-mail service provider integration in the plugin as this should be done by a third-party plugin. Even on our own support we use the Mandrill plugin for WordPress to deliver e-mail notifications.
