### ISSUE TITLE
Separate settings, add ons and system status under a new item on left admin panel

### ISSUE THREAD

**Issue by calvintam236** [ThemeAvenue/Awesome-Support#118]
I believe the plugin should have another tab after Settings (like MailChimp for WP Lite). Settings, add ons and system status should separate from Tickets tab.

**Comment by SiamKreative** [comment]
Could you please illustrate?

**Comment by calvintam236** [comment]
I refers to this:
![untitled](https://cloud.githubusercontent.com/assets/6436149/7061661/b8c3c514-de49-11e4-8380-4b3c20e69113.png)

**Comment by julien731** [comment]
So you would like the settings to be where? Under the WordPress **Settings** menu item?

**Comment by calvintam236** [comment]
No, another tab below settings (shown on above screenshot)
Settings part should not show under Tickets

**Comment by julien731** [comment]
We have decided to keep everything under one tab only for simplicity.
