### ISSUE TITLE
Public ticket view only shows title + content

### ISSUE THREAD

**Issue by eteubert** [ThemeAvenue/Awesome-Support#120]
I don't get the custom single-ticket view I see in the teaser video. All I see is title + content, like in a blog post. I switched to "twentyfourteen" theme to make sure it's not theme related.

![screen_shot_2015-04-15_at_15_24_09](https://cloud.githubusercontent.com/assets/235918/7154072/bd8d3720-e384-11e4-8c9e-923b83ee8498.png)

**Comment by eteubert** [comment]
Found the issue: Deactivating the plugin https://wordpress.org/plugins/wp-open-graph/ helps.

**Comment by julien731** [comment]
Thanks for giving the solution to this problem. However, it doesn't seem right the Awesome Support breaks when WP OpenGraph is enabled. I will keep this in a corner of my head and try to find out what the conflict is.

Thanks.
