### ISSUE TITLE
Usage of deprecated WP functions

### ISSUE THREAD

**Issue by DanielBakovic** [ThemeAvenue/Awesome-Support#123]
PHP Notice:  update_usermeta is <strong>deprecated</strong> since version 3.0! Use update_user_meta() instead. in ..wp-includes\functions.php on line 3378
PHP Stack trace:
PHP   1. {main}() ..wp-admin\profile.php:0
PHP   2. require_once() ..wp-admin\profile.php:18
PHP   3. do_action() ..wp-admin\user-edit.php:137
PHP   4. call_user_func_array() ..wp-includes\plugin.php:496
PHP   5. WPAS_User->save_user_custom_fields() ..wp-includes\plugin.php:496
PHP   6. update_usermeta() ..wp-content\plugins\awesome-support\includes\admin\class-admin-user.php:86
PHP   7. _deprecated_function() ..wp-includes\deprecated.php:2377
PHP   8. trigger_error() ..wp-includes\functions.php:3378

PHP Notice:  delete_usermeta is <strong>deprecated</strong> since version 3.0! Use delete_user_meta() instead. in ..wp-includes\functions.php on line 3378
PHP Stack trace:
PHP   1. {main}() ..wp-admin\profile.php:0
PHP   2. require_once() ..wp-admin\profile.php:18
PHP   3. do_action() ..wp-admin\user-edit.php:137
PHP   4. call_user_func_array() ..wp-includes\plugin.php:496
PHP   5. WPAS_User->save_user_custom_fields() ..wp-includes\plugin.php:496
PHP   6. update_usermeta() ..wp-content\plugins\awesome-support\includes\admin\class-admin-user.php:86
PHP   7. delete_usermeta() ..wp-includes\deprecated.php:2389
PHP   8. _deprecated_function() ..wp-includes\deprecated.php:2276
PHP   9. trigger_error() ..wp-includes\functions.php:3378

**Comment by julien731** [comment]
Thanks for reporting that. It's already been fixed in the master branch and will be included in next update.
