### ISSUE TITLE
Statuses are not styled on front-site

### ISSUE THREAD

**Issue by DamirPecnik** [ThemeAvenue/Awesome-Support#126]
The styling issues on frontend see screenshot!

![2015-04-25 20 53 15](https://cloud.githubusercontent.com/assets/10489911/7334202/60d1b086-eb8d-11e4-8dde-0b364f1c2c9f.jpg)
![2015-04-25 20 52 57](https://cloud.githubusercontent.com/assets/10489911/7334203/60d5b44c-eb8d-11e4-9c60-489681207b24.jpg)

**Comment by julien731** [comment]
Have you correctly selected the tickets list page in the plugin general settings?

**Comment by DamirPecnik** [comment]
It appears i have problem with stylesheet i get it lik ethis:
http://projects.dev/webthemerF:Websitesprojectswebthemerwp-contentpluginsawesome-support/themes/default/css/style.css?ver=3.1.6

Any idea why?

**Comment by julien731** [comment]
This was fixed in 3652c8b74a6e196439aa91c6bfae8179eec0e5f5
