### ISSUE TITLE
Add compatiblity for AskBug Theme

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#127]
Add support for this theme would be awesome:
http://anspress.io/downloads/askbug/

The author of anspress is a very good friend and it would be awesome, if you both could work together to create an awesome (may the best) support theme, which supports the awesome support plugin and may you both could also create the documentation plugin together. 

Would be absolutely awesome :)

https://github.com/anspress/anspress/issues/280

**Comment by julien731** [comment]
We're completely open to this kind of work. Could you get us in touch with your friend?

**Comment by SiamKreative** [comment]
I'm in!

**Comment by TheZoker** [comment]
What would be the best way to communicate?

**Comment by SiamKreative** [comment]
A Slack #channel perhaps?

**Comment by TheZoker** [comment]
Yea would be great for me :)

**Comment by SiamKreative** [comment]
Hi @rahularyan,

The site has now moved to http://anspress.io/. I would like to move forward with this, now that we have more flexibility with custom fields. I have installed your theme and I will be working on the integration.

**Comment by rahularyan** [comment]
@SiamKreative Thanks for you interest, but AnswerBox is just a base theme and I don't like to extend it much. But askbug and our upcoming theme can have this,  I will discuss this with my team and let you know.

**Comment by SiamKreative** [comment]
We're discussing this matter by email. And as we will be working on their theme (on a branch in their repository), I'm closing this issue.
