### ISSUE TITLE
No html format by sending emails through mandrill  

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#132]
I switched to mandrill for sending emails (https://wordpress.org/plugins/wpmandrill/) and now all Awesome-Support emails are not html formatted anymore :/
![img_2015 05 01_20h44m11s_002_](https://cloud.githubusercontent.com/assets/1368405/7435320/05eada48-f043-11e4-95c0-856984a71174.png)

This is what the request looks in the mandrill api report:
![img_2015 05 01_20h50m34s_005_](https://cloud.githubusercontent.com/assets/1368405/7435406/c3d8df00-f043-11e4-8859-a7718e95cb4a.png)

Can you may help me solve the problem?

Thank you :)

**Comment by julien731** [comment]
Humm that's surprising. We're using Mandrill also for our support and it works ok. The HTML tags I see in the Mandrill report are things you've added in the e-mail templates right?

**Comment by TheZoker** [comment]
Yes exactly. I send you some login data according to #111 so you can also have a look at this issue :)

**Comment by julien731** [comment]
Backslashes seem to be wrongly escaped. This also happens in the content with `"`. Escapement should be reworked.

**Comment by julien731** [comment]
Fixed by 0ea50a9a6fff2d7729170da3357ca6ce8d8dbcf0
