### ISSUE TITLE
"In Progress" tickets inside Bin should not count as "In Progress"

### ISSUE THREAD

**Issue by eteubert** [ThemeAvenue/Awesome-Support#137]
Screenshot explains it, the numbers are wrong:

![tickets_ _podlove_podcast_publisher_ _wordpress](https://cloud.githubusercontent.com/assets/235918/7557897/c316fb30-f7cb-11e4-81d1-7ec78247e29c.png)

Both tickets in "All" are closed.
I have, however, two "new" tickets inside the Bin.
When I close these, the notification number disappears, but the "In Progress" filter is still wrong.

![tickets_ _podlove_podcast_publisher_ _wordpress](https://cloud.githubusercontent.com/assets/235918/7557926/9b09e570-f7cc-11e4-921a-eade159c80d1.png)

**Comment by SiamKreative** [comment]
Thanks for reporting this issue. This really helps us improve our plugin. We'll get it solved asap :)

**Comment by digitalchild** [comment]
Closed tickets also seem to show as in the 'in progress' count. Does this fix also address that?
