### ISSUE TITLE
Add-on license checking overhead

### ISSUE THREAD

**Issue by robertpersson** [ThemeAvenue/Awesome-Support#140]
Just want to start with letting you guys know that I find this plugin great!
However, we've had some performance issues with add-ons.

Using the Query Monitor Plugin I found that awesome-support spends about 8 seconds in HTTP request time depending on the number of active add-ons (accounting the majority of the total request time).

The problem seem like the license is validated on every page request (at least in the back-end), not only is this misuse of resources but it does it twice(!) for each addon. I've had to disable two add-ons to get the times down... Attached is a print screen with stack traces for the awesome-support plugin.

![stacktrace](https://cloud.githubusercontent.com/assets/3025525/7589818/50ba051e-f8c5-11e4-8904-c3bf3bf51165.png)

The following is found in class-option-edd-license.php:

```
public function activateLicense( $option ) {
	if ( $this->settings['id'] != $option->settings['id'] ) {
		return;
	}
```

It seems that the function should return if not the license has not changed, but doesn't seem to be considered by all **do_action('tf_create_option_wpas')**. Why I dont know.

If it might help, I'm using ssl on our page.

Feels like this might be a TitanFramework issue? Is there a fix?

**Comment by julien731** [comment]
Thanks for reporting that. It looks like a Titan Framework issue but I'll definitely look into it.

**Comment by robertpersson** [comment]
Hey again, feeling a bit dumb, but since I've had other problems with my site since it went live I did a bit of digging.

A mayor difference from my devenv is of course caching, in particular object caching, which has raised some strange issues with functionality. I don't know if that's the cause for this issue reported here but I wouldn't be suprised if that was the case.

Just wanted you guys to know!

Br, Robert

**Comment by julien731** [comment]
Thanks for the update Robert. Does this mean that the overhead is gone on the live server?

**Comment by SiamKreative** [comment]
Should we close this as the site performance issue seems to be gone?

**Comment by robertpersson** [comment]
Sorry for the late reply, the caching mechanism was at fault.
No major overhead at the moment after having tuned the cahcing settings...
