### ISSUE TITLE
Problem with awesome-support-email plugin when SITE URL != WORDPRESS URL

### ISSUE THREAD

**Issue by robertpersson** [ThemeAvenue/Awesome-Support#151]
When site url and wordpress url differs in gereral settings, an error is thrown on line 222 in email-support.php.

I temporarily resolved this by setting

```get_bloginfo( 'url' )```

to

```get_bloginfo( 'wpurl' )```

on that specific line.

// Br,
// Robert

**Comment by julien731** [comment]
Thanks for reporting this @robertpersson that's indeed a case that we didn't test. I will move this issue to the private repo that we use to host the e-mail support and close this one. Don't worry, it will be taken care of ;)

**Comment by robertpersson** [comment]
Hey again!

Sounds good :+1: However, an even better solution is to change the line remove line 222 entirely and modify line 223 to something like:

```require_once( ABSPATH . '/wp-admin/includes/plugin.php' );```

the other solution a proposed gave erros when using https on the site...

// Have a nice weekend,
// Robert

**Comment by julien731** [comment]
Thanks for your input. We'll definitely use it.
