### ISSUE TITLE
Conflict with Jetpack Publicize

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/Awesome-Support#152]
It seems that when Jetpack Publicize is enabled, users are redirected on the submission page after saving a post.

See https://wordpress.org/support/topic/unable-to-save-posts

**Comment by camaran** [comment]
have you some information for this problem because i cannot use this plugin without jetpack

**Comment by julien731** [comment]
It seems that the conflict only affects admins. I've been testing saving a draft as a support agent and didn't encounter any problem.

**Comment by camaran** [comment]
yes but for admin is a problem beacuse cannot publish news
