### ISSUE TITLE
Include reCaptcha support

### ISSUE THREAD

**Issue by ET-Bent** [ThemeAvenue/Awesome-Support#154]
This plugin could not be used if reCAPTCHA is active at the same time. Login fails because the post is missing the validated reCAPTCHA attributes. 

Information about integrating reCAPTCHA can be found here:
https://github.com/mcguffin/wp-recaptcha-integration/wiki/Custom-Themes-and-Forms

**Comment by drosendo** [comment]
Hi,

Im using version 5.1.1 with Google Captcha (reCAPTCHA) by BestWebSoftSettings

And this issue occours...

Cheers,
David

**Comment by drosendo** [comment]
Fixed using the add_action:


```
add_action( 'wpas_after_login_fields', 'insert_captcha' );

function insert_captcha() {
	echo do_shortcode( '[bws_google_captcha]' );
}

```

Cheers,
David
