### ISSUE TITLE
Disable registration Notice

### ISSUE THREAD

**Issue by digitalchild** [ThemeAvenue/Awesome-Support#155]
On the settings page you have allow registrations on support page however when this is disabled a notice shows up. This is confusing for users even though the login form is below it. 

There needs to be a way to disable the notice while still disabling registration. 

Maybe a radio box ?

Allow registration 
Disable registration with notice 
Disable registration without notice (just show the login form) 

If you want me to write this I can submit a pull request with the changes including upgrade code.

**Comment by julien731** [comment]
I see what you mean. What would be best in your opinion? An option in the settings (wouldn't this be confusing for the user as well) or maybe a filter?

**Comment by SiamKreative** [comment]
I think a radio input would be the best in terms of user experience. It could look like this:

![image](https://cloud.githubusercontent.com/assets/1778633/8275142/fa8e87a8-18c9-11e5-9d6e-fc1e521fd3af.png)

**Comment by digitalchild** [comment]
Hah! that's exactly what I had in mind.
