### ISSUE TITLE
Error loading stylesheets when home_url != site_url.

### ISSUE THREAD

**Issue by robertpersson** [ThemeAvenue/Awesome-Support#163]
Shouldn't line 251 in functions-templating.php be replaced with the following?

```
$uri = trailingslashit( site_url() ) . $truncate;
```

An absolute path is needed to the stylesheet resource, not the canonical one...
This fixed the loading of resources issue on my config at least.

**Comment by julien731** [comment]
Thanks for pointing it out @robertpersson
