### ISSUE TITLE
Issue while submitting reply

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/Awesome-Support#166]
See attached screencast and screenshot. Latest WordPress and latest dev version of the plugin. Working on the bootstrap3 branch.

![issue-while-submitting-reply](https://cloud.githubusercontent.com/assets/1778633/8715255/f171137e-2ba8-11e5-8caf-83716a62aea3.png)

[Link to screencast](http://giphy.com/gifs/3oEdvcIivwuveJ1OH6)

**Comment by julien731** [comment]
Can't recreate. Please make sure you're using the latest dev version.

**Comment by SiamKreative** [comment]
As mentioned, this is happening using the latest dev version... More importantly, it looks like it's linked to the fact that **it's possible to upload a file much larger than allowed**. I attached a 20Mo file while my setting only allows 2Mo.
