### ISSUE TITLE
Improve System Status Report

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/Awesome-Support#173]
When users are asked to copy the system status report, they usually just paste the plain text JSON string in the WordPress support forums. This is hard to read. It would be great if we could have an extra option in the system status page that's "Copy for WordPress.org" or something similar. This would simply add the markdown quotes around the JSON string.

**Comment by SiamKreative** [comment]
Done, see 9f34383e6abba55984f83dea8523a1454e320e4e
