### ISSUE TITLE
UX - Tickets menu remains closed while editing ticket

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/Awesome-Support#180]
I remember raising this issue, but I'm unable to find it again. So here we are...

During ticket edition, the sub menu "All tickets" seems to be selected, but the menu "Tickets" is not open. This is a bit disturbing.

Below a screenshot that shows the difference between AS & WC:
![image](https://cloud.githubusercontent.com/assets/1778633/9326811/c5998b68-45c6-11e5-8455-6377890ba7aa.png)

I wonder how they do it. Perhaps @bryceadams will be able to tell me?

**Comment by bryceadams** [comment]
I recall personally having to do this (in other plugin) with JS to highlight the menu item in submenu, but submenu should still appear. I'd suspect this is something to do with how you've added the custom post type maybe?

**Comment by SiamKreative** [comment]
This was caused by a new add-on under development.
