### ISSUE TITLE
Use Grunt to Update Version Numbers

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/Awesome-Support#200]
Instead of manually updating all version numbers (and forgetting some), let's automate that with Grunt.

**Comment by SiamKreative** [comment]
8601660f6b99cc4ecabff5ce2219e318dce64985
8d9fd919a0a4ffcee1972e702ad6d84d9f622687

Would be awesome to add https://github.com/dylang/grunt-prompt for prompting which semver 2.x release types (`major`, `minor`, `patch`, or `prerelease`) to do.
