### ISSUE TITLE
wpas_create_notification deprecated, but used

### ISSUE THREAD

**Issue by tivnet** [ThemeAvenue/Awesome-Support#208]
@julien731 You made it deprecated in 3.2, but did not remove the calls, for example, in `functions-user`, so PHP displays notices. With DEBUG on, nothing works.

**Comment by julien731** [comment]
db7435e55c9623f91946a8f467b8f755c7fe85bd closed it. I messed up the commit message.

**Comment by tivnet** [comment]
@julien731 Great!
