### ISSUE TITLE
Show only my tickets in the /ticket/ archive

### ISSUE THREAD

**Issue by tivnet** [ThemeAvenue/Awesome-Support#209]
People must not see other people's tickets. This is a critical issue, in my opinion.

**Comment by tivnet** [comment]
P.S. I am going to disable the /tickets/ arhive completely on my site. Do not see any use of it.

**Comment by tivnet** [comment]
Something like:

```
add_action( 'pre_get_posts', 'show_only_my_tickets' );

/**
 * Show only my tickets in /ticket/ archive
 * @param WP_Query $query
 */
function show_only_my_tickets( WP_Query $query ) {

	if ( ! is_admin() &&
	     $query->is_main_query() &&
	     $query->is_post_type_archive( array( 'ticket' ) )
	) {

		$query->set( 'author', get_current_user_id() );

	}

}
```

**Comment by tivnet** [comment]
Or maybe just redirect to `/my-tickets/`

**Comment by julien731** [comment]
Just to confirm: are you correctly redirected to your tickets page? This should be done by [Awesome_Support::redirect_archive()](https://github.com/ThemeAvenue/Awesome-Support/blob/master/includes/class-awesome-support.php#L791)

**Comment by tivnet** [comment]
@julien731 Ha, that's exactly what I was missing.... but it was not working for me, and I was seeing the archive. Will try to debug.

**Comment by julien731** [comment]
Yeah in that case that'd be a mess. I'd need to double check first but I think we could set the post type `has_archive` to `false`. Just need to make sure that wouldn't introduce any regressions.

I'm still curious why this doesn't work for you though...

**Comment by tivnet** [comment]
Do not close the ticket yet. I will check it later today.

**Comment by tivnet** [comment]
@julien731 
Same reason

`wpas_redirect( 'archive_redirect', get_permalink( wpas_get_option( 'ticket_list' ) ) );`

should be

`wpas_redirect( 'archive_redirect', get_permalink( wpas_get_option( 'ticket_list' )[0] ) );`

(wpas_get_option returns array)

**Comment by tivnet** [comment]
@julien731 ... and a minor thing: check for `get_current_user_id` and go directly to login instead of double redirect.

**Comment by julien731** [comment]
98856b4bb497d46f6a22e0c858741c2dc9b1591b fixed it.
