### ISSUE TITLE
wpColorPicker() error

### ISSUE THREAD

**Issue by tivnet** [ThemeAvenue/Awesome-Support#221]
@julien731 

I've got a JS error on the `wp-admin/edit.php?post_type=ticket` page

`Uncaught TypeError: $(...).wpColorPicker is not a function`

```
jQuery(document).ready(function($) {
			"use strict";
			$('.tf-colorpicker').wpColorPicker();
		});
```

and had to force 
`wp_enqueue_script( 'wp-color-picker' );`

to fix it temporarily. Otherwise, even checkboxes did not work.

Please take a look if you also have it.

**Comment by tivnet** [comment]
@julien731 I did some debugging.

`TitanFrameworkOptionColor::display` is **never called**.

`TitanFrameworkOptionColor::startColorPicker` is called by `tf_add_action_once( 'admin_footer', array( $this, 'startColorPicker' ) );` - and tries to use the color picker, which was never loaded.

**Comment by tivnet** [comment]
... wrote to Titan.

**Comment by bfintal** [comment]
I've fixed this already, although it's in the https://github.com/gambitph/Titan-Framework/tree/oop-getoption-setoption branch. Will merge it soon.

I'd appreciate it if you guys can use that branch as well to test out whether your options work fine. It has a lot of speed improvements.

**Comment by tivnet** [comment]
@bfintal Thanks Benjamin.

@julien731 Until new Titan is released and tested, should add this where the Titan is loaded

```
# @todo - convert to PHP 5.2 call
add_action( 'admin_enqueue_scripts', function () {
	wp_enqueue_script( 'wp-color-picker' );
} );
```

**Comment by julien731** [comment]
Thanks for your help @tivnet we will update AS as soon as a new version of TF is out.
