### ISSUE TITLE
Non-translatable and wrong message in JS

### ISSUE THREAD

**Issue by tivnet** [ThemeAvenue/Awesome-Support#223]
`alert('You can\'t submit an empty ticket reply.');`

in `assets/public/js/public.js`

### TODO:

1. Localize JS, so this message can be translated.
1. It's shown on a new ticket submit, too, so it's not "reply" but just "empty ticket".

**Comment by SiamKreative** [comment]
Thanks for reporting this. We'll submit a fix asap.

**Comment by SiamKreative** [comment]
Localize translations 08fc586f21a649c67704a25a1b0e554405523d23
