### ISSUE TITLE
3.2.3 Issues

### ISSUE THREAD

**Issue by vicky081** [ThemeAvenue/Awesome-Support#226]
Hi,

I was using 3.2.2 in my side, yesterday i noticed there is an update(so i updated), now i face some problem with compatibility, there is a toggle issue happening in my side, which means i enabled multiple product support in general tab and saved, in a frontend there is a normal text editor(previously with version 3.2.2 it was wp editor (enable that option)) now with latest it is just textarea, also file upload is missing if i visit file upload tab and click save, i can see the fileupload in frontend but product selection is not there(toggle issue), can you guys do cross by checking the latest in fresh installation in your testing server might reproduce the problem. 

Hope it helps.

NOTE: Compare to the old version there is just wpcolorpicker error which you fixed in latest(i know that) so i am downloaded old version of 3.2.2 and replaced the titan framework entire folder to that old and using in my side.

Thanks,
Vicky

**Comment by SiamKreative** [comment]
We'll look into this tomorrow first thing in the morning. Sorry to keep you waiting.

**Comment by julien731** [comment]
Please update to 3.2.4 and try again. If you're still having problems please use the WordPress.org support forums. We only use GitHub for bug tracking and not for support: http://wordpress.org/support/plugin/awesome-support
