### ISSUE TITLE
Improve error messages management

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/Awesome-Support#28]
Error messages management is a little messy and needs improvements. EDD has a very nice way of handling errors using sessions: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/error-tracking.php

**Comment by SiamKreative** [comment]
See issue #63

**Comment by SiamKreative** [comment]
Notifications are not working on our own site: http://getawesomesupport.com/submit-ticket/?message=IjxzdHJvbmc%2BRVJST1I8XC9zdHJvbmc%2BOiBJbnZhbGlkIHVzZXJuYW1lIG9yIGluY29ycmVjdCBwYXNzd29yZC4i
