### ISSUE TITLE
New theme - bootstrap3

### ISSUE THREAD

**Issue by Ninos** [ThemeAvenue/Awesome-Support#32]
Have you thought about a theme (template files), which's based on bootstrap3? I may could create one, if you want...

**Comment by SiamKreative** [comment]
Hey @Ninos,

Any progress on this? I'm going to close this for now. You can re-open if this is something you're still planning on doing :)

**Comment by Ninos** [comment]
Sorry for the late reply. I had no time before to work for a bs based theme. Atm I'm working for a bootstrap theme (based on your branch bstheme). The problem is, that lots of templates are directly written into the /includes/functions-templating.php. I would recommend to explude the template parts out of the functions. (May in /themes/yourtheme/global/textarea|message|*).
How you plan to handle such problem? :)

PS: If you want I can create a PR of my current changes, so you can merge them into bstheme..
