### ISSUE TITLE
Assets not enqueued when using the shortcode on a non-AS page

### ISSUE THREAD

**Issue by bryceadams** [ThemeAvenue/Awesome-Support#38]
The assets are enqueued conditionally according to it being an 'awesome support page', so they won't be enqueued if a shortcode is used on a different page.

You should enqueue the styles directly from the shortcodes - http://mikejolley.com/2013/12/sensible-script-enqueuing-shortcodes/

**Comment by SiamKreative** [comment]
I think the easiest way to go is async loading with https://github.com/filamentgroup/loadCSS. We can load just about anything and it doesn't affect the site's performance.

**Comment by julien731** [comment]
Let's replace the plugin-specific pages options in the settings by a Select2 and allow for multiple pages to be set as "Awesome Support pages". We then need to hook it on `wpas_plugin_frontend_pages` ( see #181 ).

This will allow having multiple submission pages.

**Comment by julien731** [comment]
It is now possible to have multiple submission / lists pages. See 1f90b8e 630e166 and https://github.com/gambitph/Titan-Framework/pull/272

This will require Titan Framework to be updated.

**Comment by HW-Siew** [comment]
Is this working now? I am still facing the same problem. Shortcode do not work in pages other then the designated page in setting. I can manually add style, but not script. Without script, filter and search function will not work for shortcode.
