### ISSUE TITLE
Addons do not activate 

### ISSUE THREAD

**Issue by getresults** [ThemeAvenue/Awesome-Support#47]
I have just tried to activate the currently available addons in my local dev install. 

The Addon's fail to activate and result in a "The plugin generated 234 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin." error message at the top of the plugin page screen. 

Debug log shows: 

[23-Dec-2014 05:15:15 UTC] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'WPASCR_Canned_Response' not found in /Users/phill/Documents/Websites/awesome.dev/wp-includes/plugin.php on line 496

I'm running the latest version from github (commit 0ba5507e3dc520756974d6c7e01abb5f4af235ba)

Possibly not activating because I'm running in a local dev environment instead of web accessible url that the licensing system can get a response from?

**Comment by SiamKreative** [comment]
Hey Phil @getresults, is this solved? Should I close this issue?

**Comment by julien731** [comment]
All fixed in the addons.
