### ISSUE TITLE
Improve ticket detail display

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/Awesome-Support#60]
I am not entirely satisfied by how the ticket content (eg. `single`) is displayed. While I do agree with the problem highlighted in d242dbee51d71aad066a10808aee780f3f0fbbe3, I am still not satisfied by the fact that the ticket's detail will display incorrectly in some themes (including Twenty Fifteen, see #58) because incorrectly wrapped in the theme's main container.

I've had a quick look at other possible solutions and there is one that peaked my interested. I'd like to have some feedback on it ( @Ninos ): http://wordpress.stackexchange.com/questions/162747/the-content-and-is-main-query

**Comment by Ninos** [comment]
Nice workout. Tried it out and worked for me:
```
function wpas_single_ticket( $content ) {

	global $post;

	$slug = 'ticket';

	/* Don't touch the admin */
	if ( is_admin() ) {
		return $content;
	}

	/* Only apply this on the ticket single. */
	if ( $slug !== $post->post_type ) {
		return $content;
	}

	if( ! in_the_loop() ) {
		return $content;
	}

	/* Remove the filter to avoid infinite loops. */
	remove_filter( 'the_content', 'wpas_single_ticket' );
	...
}
```

If you want I can create a PR :-)

PS: Remove filter should only be triggered after all the checks...

**Comment by julien731** [comment]
That's great news. I think we should also check for `is_main_query()` for safety. If you're on it then you can go ahead for a PR, otherwise I'll do it.

**Comment by Ninos** [comment]
I've updated my comment :D Will the ```is_main_query()``` solve the problem I described above?

**Comment by julien731** [comment]
Again, I completely agree with the fact that the template solution is much cleaner, but here is what it looks like for someone who just installed the plugin on a new WP install (using Twenty Fifteen):

![image](https://cloud.githubusercontent.com/assets/1441024/5700553/a0e6e3b0-9a72-11e4-887b-8fab03b15f27.png)

I think if we add a `is_main_query()` check, combined with `in_the_loop()` and a post type check there will be much less people seeing the ticket details in a wrong place than people having a broken layout.

`[is_main_query()](http://codex.wordpress.org/Function_Reference/is_main_query)` will take care of checking if the current loop isn't a secondary one.

**Comment by julien731** [comment]
With all that said, using `add_theme_support()` to warn users that their theme *could* potentially display tickets incorrectly is a good idea.

**Comment by Ninos** [comment]
Yes I think in combination with ```is_main_query()``` this should solve lots of problems. I'll create a PR :)

**Comment by julien731** [comment]
:+1:

**Comment by julien731** [comment]
We're back to a nice layout @Ninos ;)

![image](https://cloud.githubusercontent.com/assets/1441024/5700832/49c2ee7c-9a76-11e4-8c5c-04f1ae7dcb2a.png)

**Comment by Ninos** [comment]
And compability with most of the themes :D Nice workout :)

**Comment by SiamKreative** [comment]
This makes me feel like...

![Image of a happy dude](http://media.giphy.com/media/k9qu4GDdGVDLa/giphy.gif)
