### ISSUE TITLE
Show username after registration (UX improvement)

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/Awesome-Support#62]
### The username issue

While working on the demo video, I found a slightly annoying UX issue:

1. Register as an user via the front-end form
2. Submit a ticket or do whatever you want
3. Logout for some reason (switch browser / empty cookies / etc)
4. Come back on the site later on and try to login... Do you remember what your username is? Personally, I didn't.

The generated username (first_name + last_name) is only shown in the email WordPress is sending. Most of users won't be able to guess what their username is. And I'm pretty sure most users won't check their inbox to try to figure out what their username is.

### Suggestions

* Login via email + Password instead.
* Show the username right after user registration.

**Comment by bryceadams** [comment]
@julien731 @SiamKreative login with email 100%. optionally can use username if they know it, but email should be the main way.

**Comment by julien731** [comment]
See merge acca2e095847eee45b00dfeb8a3d1b80290157db
