### ISSUE TITLE
Issue while adding new product (with WooCommerce enabled)

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/Awesome-Support#67]
Hey there,

I'm running:

* WampServer 2.5
* WordPress 4.1
* WPAS 3.1.0 (from WordPress.org)
* WooCommerce 2.2.10

When I'm trying to add a new product to an existing list of products, I'm getting the following error `A term with the name and slug already exists with this parent`, even if this is not true.

![wpas-wc-product-creation-issue](https://cloud.githubusercontent.com/assets/1778633/5870113/65fd6a7e-a2f8-11e4-9c88-cd7c409c75bd.png)

I disabled WC plugin, and found out that the product has actually been created.

![image](https://cloud.githubusercontent.com/assets/1778633/5870125/829833b2-a2f8-11e4-92c5-5ca206d14314.png)

Any idea of what's happening @bryceadams ?

**Comment by bryceadams** [comment]
Try woocommerce 2.3 beta or master from GitHub repo. Julien should know about this, was something I fixed in WC core. If still not working let me know

**Comment by SiamKreative** [comment]
I just replaced the stable version of WC with the one from Github and boom...

![image](https://cloud.githubusercontent.com/assets/1778633/5871407/57c13e38-a30f-11e4-9253-fe804ce666f7.png)

@bryceadams @julien731

**Comment by SiamKreative** [comment]
This has been solved. Works fine with the latest version of both plugins:

* Awesome Support 3.1.4
* WooCommerce 2.3.5

**Comment by julien731** [comment]
Indeed it was fixed by 24452ffe0852fc056bc50275f1acc2d59975b794
