### ISSUE TITLE
Impossible to delete a ticket

### ISSUE THREAD

**Issue by holy88** [ThemeAvenue/Awesome-Support#69]
When i try to trash an open/closed ticket nothing is happening or a "Auto Draft" ticket is created.

**Comment by julien731** [comment]
As of version 3.1.2, tickets with no reply are marked "In Progress" when the Trash link is clicked. Let's see if it is the same problem.

**Comment by holy88** [comment]
Correct.

To delete a ticket without reply ( example draft n.1 ) simply write one and after delete. ^^

**Comment by julien731** [comment]
Bug was fixed by e1e76062711ece47e10dee87bd724f55593c14da
