### ISSUE TITLE
Gists breaking responsiveness in admin display

### ISSUE THREAD

**Issue by bryceadams** [ThemeAvenue/Awesome-Support#70]
![screen shot 2015-01-30 at 3 37 14 pm](https://cloud.githubusercontent.com/assets/1532482/5973037/ee86048a-a895-11e4-9943-59f5bbe2cf60.png)

Overlapping into right side meta boxes, etc.

**Comment by SiamKreative** [comment]
@bryceadams What are you using to embed a gist into replies? The embed URL? A shortcode?

**Comment by SiamKreative** [comment]
@julien731 I'm able to create a new ticket with a gist using the Embed URL (example: `<script src="https://gist.github.com/SiamKreative/dff76d2d1e85fb9d3c9a.js"></script>`). But if it try the same thing in the replies, it does not work (it does show up).

@bryceadams I'm unable to replicate the issue. On my install, Gists seem to be responsive "out of the box". See screenshot below:
![as-ticket-with-gist](https://cloud.githubusercontent.com/assets/1778633/6034644/d9b4f744-ac57-11e4-9cc4-6643f745c9c1.png)

**Comment by bryceadams** [comment]
I actually just pasted the plain gist URL in the ticket and it embedded it automatically (I assumed that was an AS feature).

**Comment by SiamKreative** [comment]
It isn't an AS feature. Maybe you have a [https://github.com/miya0001/oembed-gist](plugin) installed? But I agree, it would be great to have the ability to paste gist URL.
