### ISSUE TITLE
Canned Response

### ISSUE THREAD

**Issue by holy88** [ThemeAvenue/Awesome-Support#74]
{agent_name}

Is not parsing the name of the agent but keep "admin" ( for supervisor but the supervisor is not an admin? ).

**Comment by julien731** [comment]
This should have been fixed by 2676f0ff1aacdbef15186f3ab6cdc044f050722c

**Comment by holy88** [comment]
Works for me

**Comment by julien731** [comment]
Yeah me too. Perfect :)
