### ISSUE TITLE
Cant enable/disable auto-assignment

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#75]
There is no "enable/disable auto-assignment settings item in the backend.

**Comment by julien731** [comment]
No there is no option for that. This is a decision we've taken.However, I have added a new constant (7fb1f52ec24158de9b8f92b5258b949f489aa7d5) that will allow for advanced users to disable auto assignment.

Setting `WPAS_DISABLE_AUTO_ASSIGN` will completely disable the auto-assignment function.

**Comment by TheZoker** [comment]
Thats just because of this help text in the admin option (and I remember that there was such an option in the version 2.x):
![img_2015 02 10_14h10m44s_006_](https://cloud.githubusercontent.com/assets/1368405/6127743/c0e491b2-b12e-11e4-9d00-9854edf020cd.png)

**Comment by SiamKreative** [comment]
This needs to be documented @julien731
