### ISSUE TITLE
Closed tickets are shown on "In Progess" page in backend

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#77]
The "in progress" filter is selected...
![img_2015 02 10_00h39m10s_002_](https://cloud.githubusercontent.com/assets/1368405/6118387/5e922bbc-b0bd-11e4-808c-50ec6be1c824.png)

**Comment by julien731** [comment]
This is because you have to select Open or Closed in the filters in order to only see a specific status. However I understand your question. Maybe it should be set for Open tickets only by default?

**Comment by TheZoker** [comment]
Yes your right, the filter was set to "Any status". By then the "In progress" does not makes any sense...
![img_2015 02 10_00h39m10s_002_](https://cloud.githubusercontent.com/assets/1368405/6120671/361deb14-b0d9-11e4-9648-19d238c61638.png)

**Comment by julien731** [comment]
Yeah you're right. The status / state distinction has always been a problem. Maybe we should actually remove the status filter when a state (like "In Progress") is selected and only display opened tickets.

**Comment by TheZoker** [comment]
Why dont you just move the "In Progress" filter in to the normal filter?
![img_2015 02 10_14h12m49s_007_](https://cloud.githubusercontent.com/assets/1368405/6127770/072bbf10-b12f-11e4-8d56-ee7001af2ace.png)

**Comment by TheZoker** [comment]
This issue is not fixed:
![img_2015 02 14_12h05m47s_001_](https://cloud.githubusercontent.com/assets/1368405/6199406/2c26d5d2-b442-11e4-911c-0989a67032e9.png)

The  number shows 5, but only 1 element is shown..

**Comment by SiamKreative** [comment]
What's the status on this @julien731 @TheZoker ?

**Comment by TheZoker** [comment]
The number next to "In progress" is wrong:
![img_2015 03 18_15h12m52s_004_](https://cloud.githubusercontent.com/assets/1368405/6710526/a5f9cae2-cd81-11e4-83b5-3a93b0bd3abe.png)

**Comment by julien731** [comment]
Fixing this is doable but it's quite messy. WordPress doesn't allow for modifying this easily. I'm trying to figure out what's the best way to do it.
