### ISSUE TITLE
"Ticket creator" does not show, when a manager created a ticket

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#78]
So manager can create tickets and if they do, they are not shown in the "Ticket creator" dropdown in the backend, because only support users are shown there.

Please fix that and add the manager/admin to the dropdown, when he created the ticket (if not, only display support users there)

**Comment by julien731** [comment]
That's strange because the current user should be displayed in the list when creating a new ticket from the backend. Are you using the latest version?

**Comment by TheZoker** [comment]
Yes I use the latest version. 
Here is a screenshot of backend and frontend of the same ticket (I did not change anything on both views).

The user shown in frontend is a support supervisor (not admin), but the user displayed in the backend (joransbr), is just the first user in the dropdown (alphabetically), all of them are support users. 
![img_2015 02 10_04h00m32s_002_](https://cloud.githubusercontent.com/assets/1368405/6120744/d850098a-b0d9-11e4-85d6-906462302628.png)
![img_2015 02 10_04h00m42s_003_](https://cloud.githubusercontent.com/assets/1368405/6120746/d85240ba-b0d9-11e4-9025-739e4b038f43.png)
![img_2015 02 10_04h02m53s_004_](https://cloud.githubusercontent.com/assets/1368405/6120745/d8501d08-b0d9-11e4-8ba2-2de497cae1a5.png)

**Comment by julien731** [comment]
I've just updated how the users dropdown works. Let's wait for next update and see if the problem still occurs.

**Comment by TheZoker** [comment]
Does work :)
