### ISSUE TITLE
[Feature Request] Ticket information widget

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#79]
Add a ticket information widget, that shows all information of the ticket (e.g. assigned stuff, current status, ticket id etc.)

**Comment by julien731** [comment]
Not sure I follow you here. Are you talking about an actual widget for use on the front-end?

**Comment by TheZoker** [comment]
Yes exactly. So I want to add the widget to the ticket details page (may with a plugin like https://wordpress.org/plugins/restrict-widgets/)

Or may a own sidebar, created by the plugin for ticket details and overview page would be good, then I could add the ticket information widget right there :)

**Comment by julien731** [comment]
That can be done. As we use GitHub for bug tracking purpose I am going to move this discussion over to our roadmap on Trello ([card 39](https://trello.com/c/R5ylGpTN)).
