### ISSUE TITLE
Css word-wrap ?

### ISSUE THREAD

**Issue by holy88** [ThemeAvenue/Awesome-Support#80]
![screenshot-support 2015-02-10 16-24-00](https://cloud.githubusercontent.com/assets/10756132/6129824/612522c4-b141-11e4-803a-830df700cec5.png)

**Comment by SiamKreative** [comment]
Hum. I'll have a look later on tomorrow morning :) Thanks for reporting this issue.

**Comment by holy88** [comment]
Fix isn't working
