### ISSUE TITLE
Can't delete user ticket

### ISSUE THREAD

**Issue by holy88** [ThemeAvenue/Awesome-Support#81]
Sometimes it may be necessary to remove an user reply from the ticket admin areas .. now it's impossibile

**Comment by julien731** [comment]
Isn't it the same issue as #69 ?

**Comment by holy88** [comment]
No, it's impossibile to delete an user reply in a ticket. 

I'm using this string to do the job for now:

http://domain.tld/wp-admin/post.php?post=POSTID&action=edit&del_id=REPLYID&wpas-do=trash_reply&wpas-nonce=CODE

**Comment by julien731** [comment]
Oh ok. It is normal that you can't delete a user reply. The plugin was made that way, it seems to be the logical way to do things. Let's imagine you're an admin on your site and you have different agents providing support on your team. What if one of the agents decides to delete customer replies for whatever reasons?

An agent / admin can delete his own replies, but users replies can't be deleted.

**Comment by holy88** [comment]
I understand your point,but ..  imagine that the user loads by mistake photos of his wife naked, there should be the possibility of eliminating the ticket so i will made an option for that .. anyway the url is working fine so "just in case" people con use that

**Comment by julien731** [comment]
I do understand your concern, but I believe it's the user's duty to check his ticket and attachments, with the possibility to remove an attachment before submitting if needed.

The delete link as you're using it will remain active (at least for admins, only admins actually have the delete capability), but we are not planning on adding a delete link on the reply.

**Comment by holy88** [comment]
Fine :+1:
