### ISSUE TITLE
Feature requests for notification addon

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#84]
I have some feature requests:
- Ability to upload a picture instead of using an icon for bot image
- May include the authors avatar (dont know if that one is possible)
- If a client/agent answers, dont call the information "Creator" anymore (may just user or agent)
- May add "In Progress" instead of "open" status after a reply of a agent/client

And a bug at least:
- If another author replies to a ticket the wrong author is displayed on "xyz replied to ticket..." (creator is the right agent)
![img_2015 02 11_19h18m31s_004_](https://cloud.githubusercontent.com/assets/1368405/6153228/6307d7c0-b223-11e4-95f5-d289d5e12488.png)

**Comment by TheZoker** [comment]
So to be clear about the bug:
At the moment:
- creator = person who answered the ticket, 
- "... replied to..." = the support stuff assigned (if a agent answers)

It should be:
- creator = creator of the ticket (not of the answer)
- "... replied to..." =  person who replied to the ticket

So both field are not correct at the moment...

**Comment by TheZoker** [comment]
Could you may fix this asap, because its very annoying to always see the wrong names on the notification items...

**Comment by julien731** [comment]
Fixed. This will be pushed in 0.1.1

**Comment by SiamKreative** [comment]
@TheZoker We just released a new version. Please check it out :)

**Comment by TheZoker** [comment]
Yea theoretically its great ;)
But there are some issues:
- Uploaded image is not pushed
- User is listed as "assigned stuff"

![img_2015 03 04_22h39m09s_001_](https://cloud.githubusercontent.com/assets/1368405/6494149/e95b2e1a-c2bf-11e4-9bea-aacc483ceeac.png)
![img_2015 03 04_22h39m18s_002_](https://cloud.githubusercontent.com/assets/1368405/6494150/e95b9b02-c2bf-11e4-98d1-478e16e584f4.png)
![img_2015 03 04_22h42m22s_003_](https://cloud.githubusercontent.com/assets/1368405/6494151/e95de6dc-c2bf-11e4-8c2d-5039866e54ea.png)

**Comment by julien731** [comment]
Could you confirm that you are doing your tests on a live site and not in a local development environment. Regarding the user under "Support Staff" I'll check what's wrong.

**Comment by TheZoker** [comment]
For ANY reason, the icon does display right in the slack app, but does not in the web page....
Yes I use it on a live site

**Comment by julien731** [comment]
I will push an update soon to fix those bugs.

**Comment by TheZoker** [comment]
Is it may possible, to also include line breaks in the pushed content?

**Comment by TheZoker** [comment]
Any news?

**Comment by julien731** [comment]
That's done in dev. We need to test it a bit more and we will push an update.

**Comment by TheZoker** [comment]
Ok so all mentioned bugs are fixed.

But there is a new one:
![img_2015 03 18_15h06m20s_003_](https://cloud.githubusercontent.com/assets/1368405/6710435/f7f6a780-cd80-11e4-9895-d28529e354eb.png)

Smilies seems broken...
