### ISSUE TITLE
Ability to disable the assignment of admin to ticket

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#85]
We have an admin and some support supervisors.

The admin account is just for setting up the system and productively we use other accounts (supervisors). Now the system sometimes assigns the admin account to a ticket, but that should be disable-able :P 

Thank you

**Comment by julien731** [comment]
That's a very good point. We will definitely work on that.

**Comment by TheZoker** [comment]
You could combine this with a "vacation" mode, which a manager could use to tell the system to not assign him during the next x days/weeks.

And if there would be a endless vacation value and I set the admin on this mode, then this would work fine :)

May additional transfer all ticket assigned to the manager (who is in vacation for the next x days) to another manager, so the users get an answer.
