### ISSUE TITLE
Select which counter should be displayed next to the admin menu item

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#86]
In the settings the admin should be able to set, which number is shown next to the admin item:
- Tickets awaiting answer of agent
- Tickets awaiting answer of agent himself (so only tickets assigned to the user who is currently viewing the backend, not of all agents)

Because currently all tickets "In progress/open" are shown and thats not the best way ;)

And there is a "bug":
If I move a ticket to trash, the number still keeps telling me, that there are open tickets (but I moved them to trash). So just exclude items moved to trash from the counter.

**Comment by julien731** [comment]
The issue with wrong tickets count should have been fixed by 8b371c5b141064a4f1059db11ea585553081673c. Let's see how it goes when we push 3.1.3 but it looks correct to me.

**Comment by SiamKreative** [comment]
Hey Florian,

In my opinion, this shouldn't be an option. We're developing our plugin with the "[decisions not options](https://tommcfarlin.com/wordpress-philosophy-decisions-not-options/)" mindset. We don't want to end up with a bloated settings page.

But... I agree that if you're managing a team of agents, you would want to see the total amount of tickets awaiting an answer. So what we could eventually do is to create a filter instead.

Also, we're planning on adding a Statistics / Report page, in which an admin would be able to see all important data (such as total number of tickets awaiting answers).

Cheers

**Comment by TheZoker** [comment]
Hey,

Yea probably your right, as long as the calculation of the number works fine :)

**Comment by julien731** [comment]
Is the ticket count ok for you with 3.1.3 @TheZoker ?

**Comment by TheZoker** [comment]
Currently its working fine :)
