### ISSUE TITLE
Auto close ticket after x days missing

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#89]
In the version 3.x the feature that auto closes a ticket after x days, if the client does not answer is missing.

He should also get an email: "Your ticket has been auto-closed. If you have any additional question, open a new ticket or re-open the old one"

**Comment by TheZoker** [comment]
Ah I see there is a label "Old Tickets". How does that work?

**Comment by julien731** [comment]
The auto-close feature is indeed not in the core for now. We have had several issue with it in v2.x and didn't want to leave it as-is in v3. This feature will be added but we will need to re-code it and test it thoroughly before integrating it in core.

Regarding the "Old Tickets" feature, it's something that lets you decide a delay after which tickets are considered old and will be identified by a tag in the tickets list (admin screen). It won't automate anything but can give you a quick overview of tickets that might need to be closed.
