### ISSUE TITLE
Incompatibility with other plugins

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#90]
In the last week I had some issues with activating apps.
I always got a:
```
Fatal error: Call to a member function is_main_query() on a non-object in /wp-includes/query.php on line 730
```

One time with this plugin:
https://github.com/wp3/anspress

And another with this:
https://github.com/download-monitor/dlm-page-addon

First I thought it may be caused be the linked plugins, but the error was always gone, if I temporally deactivated awesome support.

So I think this issue is anyhow caused by as...

Can you may have a look at this?

**Comment by julien731** [comment]
We sure will have a look at this. Actually a similar issue was reported with WooCommerce ( #72 ). We have something that seems ok but needs a little more testing. This fix will be coming asap.

**Comment by julien731** [comment]
Has it been fixed with the latest update?

**Comment by TheZoker** [comment]
I can activate both plugins without any error, so I guess its fixed (if I notice any issue, I let you know :) )
