### ISSUE TITLE
Temporary form for user information

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#91]
And heres another feature request:
- The agent has the ability to create a temporary form, that the user has to fill out (can can drag and drop the fields and give them a name).
E.g. ftp-account, ftp-password...

The form is displayed on the ticket frontpage to the user and he is told to fill it out and submit it.

After he done that, the fields are editable (if he made a mistake). The admin now can see the filled in form in the backend and can use the data. After using them he can just delete the fields and the user gets an information, that his login data has been deleted.

**Comment by julien731** [comment]
Thanks for the suggestion. I think it's similar, although not exactly the same, to this add-on that we've planned: https://trello.com/c/ToMHlLfP Does it sound like what you're thinking? It was initially limited to credentials but can be extended to more uses.
