### ISSUE TITLE
Break the Custom Fields Save Class Down

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/Awesome-Support#92]
Currently, all the heavy lifting for saving custom fields is done by one and only one method in the `WPAS_Save_Fields` class (actually two: one for the front-end and one for the back-end).

It would be much more flexible to have one method that only takes an option array and does all the processing. A higher method would gather all options and loop through them.

This would also have the huge advantage of making the class capable of saving any custom field and not only the ones registered with Awesome Support. This would be really useful for addons for instance.

## Proposed Class Structure

- `save()`: This method would be the high level one that gathers all custom fields and loops through them for the back-end *and* the front-end

- `update()`: This new method would be the one that takes one option array, runs all necessary checks (including checking for a custom saving callback) and updates the custom field value if needed

**Comment by SiamKreative** [comment]
Make sure to update the (custom fields doc)[http://getawesomesupport.com/documentation/awesome-support/custom-fields/] accordingly.
