### ISSUE TITLE
Plugin is not ready for localization

### ISSUE THREAD

**Issue by wpvipteam** [ThemeAvenue/Awesome-Support#94]
I translated everything from beginning to end. Everything is translated perfectly. I worked with Poedit. The translation is 100%. Total of 357 strings. But, many parts are untranslated. Pot file is incomplete. By the way, textdomain missing. Many parts of the site are still in English. And that's disappointing.

Login Form
================================
In pre-filled fields: E-mail or username
Please fill out this field.

Register Form
================================
In pre-filled fields: First Name, Last Name
Text of the checkbox: Show Password
Allert: Please fill out this field.
Creating Account ...

WordPress Dashboard / Awesome Support Settings Pages
================================
All Tickets: Support Staff, Awaiting Support Reply
Add New: (In sidebar) Ticket Creator, Support Staff
Tags: Add New Tag, Search Tags
Settings: Everything is still in English
System Status: Tools

Please try to solve this. Regards

**Comment by julien731** [comment]
See https://wordpress.org/support/topic/plugin-is-not-ready-for-localization
