### ISSUE TITLE
Date and Time Stamp

### ISSUE THREAD

**Issue by wpvipteam** [ThemeAvenue/Awesome-Support#95]
Plugin does not take time from WP General Settings. It does not take into account the current time and time zone.

Instead, the plugin works with GMT. And doing strange and ...

I opened the test ticket. And then I as a user added a new comment. Plugin displays:

January 1, 1970 18:39
1 hour ago

First message, open ticket, shows:

February 24, 2015 18:39
2 hours ago

This is definitely one bug.

**Comment by julien731** [comment]
See https://wordpress.org/support/topic/date-and-time-stamp-1
