### ISSUE TITLE
Subject line is empty

### ISSUE THREAD

**Issue by wpvipteam** [ThemeAvenue/Awesome-Support#97]
Reference: https://wordpress.org/support/topic/subject-line-is-empty

Abstract: Settings for email is to send all notices. Plugin (v3.1.4) sends email notifications. But, the subject line is empty.

Test and Test Result
===================
Just as I thought. Error is on your side.

I have run the test website only for the purpose of testing. Only default WP installation and only two of the plugin. WP Mail SMTP and Awesome Support.

- WordPress v4.1.1
- WP Mail SMTP v0.9.5
- Awesome Support v3.1.4

And what happens?

WP Mail SMTP
===================
WP Mail SMTP properly sends a message through the Mandrill.
To Admin: This is a test email generated by the WP Mail SMTP WordPress plugin.

WordPress
===================
WordPress properly sends messages after registering a new user
(1.) To Admin: New user registration on your site Test Website: Username, E-mail
(2.) To User: Login Credentials: Username, Password, Login URL

Awesome Support
===================
Sending messages with an empty subject line. Subject line IS NOT INCLUDED.

(1.) To Admin: Hi admin,
The request Blah, blah test ticket (http :// MY TEST SITE.COM/wp-admin/post.php?post=6&action=edit) has been assigned to you.

View Ticket http :// MY TEST SITE.COM/wp-admin/post.php?post=6&action=edit

or follow this link: http :// MY TEST SITE.COM/wp-admin/post.php?post=6&action=edit
Regards,
My Test Site

(2.) To User: Hi Mark User,
Your request (http :// MY TEST SITE.COM/ticket/blah-blah-test-ticket/) has been received, and is being reviewed by our support staff.
To add additional comments, follow the link below:

View Ticket http :// MY TEST SITE.COM/ticket/blah-blah-test-ticket/

or follow this link: http :// MY TEST SITE.COM/ticket/blah-blah-test-ticket/
Regards,
My Test Site

Conclusion: 
===================
Awesome Support plugin definitely NOT INCLUDE subject line when sending email messages. Please fix it. Thanks in advance.

Regards

**Comment by julien731** [comment]
See https://wordpress.org/support/topic/subject-line-is-empty?replies=5
